version: '3'

services:
  wordpress:
    build: wordpress/
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db

  db:
    build: mariadb/
    container_name: mariadb  
      #restart: always
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    build: nginx/
    container_name: nginx
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx/config/nginx.conf:/etc/nginx/config/nginx.conf
      - ./nginx/mycert.crt:/etc/nginx/ssl/certificate.crt
      - ./nginx/mykey.key:/etc/nginx/ssl/private.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - wordpress

networks:
  app-network:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
