FROM alpine:3.12

RUN apk add --no-cache \
	php7 \
	php7-fpm \
	php7-mysqli \
	php7-json \
	php7-openssl \
	php7-curl \
	php7-zlib \
	php7-xml \
	php7-phar \
	php7-intl \
	php7-dom \
	php7-xmlreader \
	php7-ctype \
	php7-mbstring \
	php7-gd \
	curl

RUN addgroup -S www-data && adduser -S -G www-data www-data

WORKDIR /var/www/html

RUN curl -O https://wordpress.org/latest.tar.gz \
	&& tar -xzf latest.tar.gz --strip-component=1 \
	&& rm latest.tar.gz \
	&& chown -R nobody:nobody /var/www/html

COPY config/php-fpm.conf /etc/php7/php-fpm.d/www.conf
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 9000

VOLUME /var/www/html

ENTRYPOINT ["docker-entrypoint.sh"]
