FROM	alpine:3.12

RUN apk add --no-cache mariadb mariadb-client

RUN mkdir -p /run/mysqld
RUN chown -R mysql:mysql /run/mysqld

COPY conf.cnf /etc/mysql/config.cnf

COPY startup.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/startup.sh

EXPOSE 3306

ENTRYPOINT ["startup.sh"]
